export const FETCH_JOB_POSTS = 'FETCH_JOB_POSTS';
export const ADD_JOB_POST = 'ADD_JOB_POST';
export const DELETE_JOB_POST = 'DELETE_JOB_POST';
export const EDIT_JOB_POST  = 'EDIT_JOB_POST';
export const UPDATE_JOB_POST  = 'UPDATE_JOB_POST';
export const FILTER_JOB_POSTS  = 'FILTER_JOB_POSTS';